repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "0.4.0"
    hooks:
      - id: sync_with_poetry

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        args:
          - --fix

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
