[project]
name = "django-heavy-water"
version = "0.1.0"
description = ""
authors = [{ name = "Josh Asplund", email = "joshasplund@gmail.com" }]
license = "BSD-3-Clause"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["Django>=3.0"]

[project.urls]
Repository = "https://github.com/joshuata/django-heavy-water"

[dependency-groups]
dev = ["mypy", "django-stubs"]

[build-system]
requires = ["uv_build>=0.11,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "heavy_water"

[tool.ruff]
target-version = "py310"
src = ["src"]

[tool.ruff.lint]
select = ["F", "E", "W", "C90", "I", "UP", "DJ", "T20", "TD", "S"]
ignore = ["E501", "TD003"]

[tool.mypy]
files = ["src"]
mypy_path = "src"
python_version = "3.10"
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
warn_return_any = true
strict_equality = true
