HEAVY_WATER_CREATE_ROOT_USER = True
HEAVY_WATER_SUPERUSER_USERNAME = "root"
HEAVY_WATER_SUPERUSER_EMAIL = "root@example.com"
HEAVY_WATER_SUPERUSER_PASSWORD = "rootroot"  # noqa: S105
HEAVY_WATER_SUPERUSER_FIRST_NAME = "Root"
HEAVY_WATER_SUPERUSER_LAST_NAME = "User"
HEAVY_WATER_FIXTURE_MODULE = ["fixtures"]
